// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace TestMlML.Model
{
    public class ModelInput
    {
        [ColumnName("id"), LoadColumn(0)]
        public float Id { get; set; }


        [ColumnName("Label"), LoadColumn(1)]
        public string Label { get; set; }


        [ColumnName("x_pos"), LoadColumn(2)]
        public float X_pos { get; set; }


        [ColumnName("y_pos"), LoadColumn(3)]
        public float Y_pos { get; set; }


    }
}
