// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestMl;

namespace TestMl.Migrations
{
    [DbContext(typeof(BloggingContext))]
    [Migration("20191113173100_ded")]
    partial class ded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TestMl.PointData", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("Label")
                        .HasColumnType("real");

                    b.Property<float>("x_pos")
                        .HasColumnType("real");

                    b.Property<float>("y_pos")
                        .HasColumnType("real");

                    b.HasKey("id");

                    b.ToTable("PointData");
                });
#pragma warning restore 612, 618
        }
    }
}
